### ISSUE TITLE
Некорректный импорт модуля

### ISSUE THREAD

**Issue by vanya2h** [lodosstm/yandex-checkout-node#2]
В документации указывается, что импорт модуля происходит при помощи системы CommonJS, но когда я использую `const checkout = require("yandex-checkout)`, я получаю `undefined`, потому что в репозитории отсутствует `index` файл. 

Для исправления проблемы приходилось немного покопаться в исходниках и использовать `const checkout = require("yandex-checkout/lib")`

**Comment by roman-kudlay-lodoss** [comment]
**package.js** пакета содержит следующий блок:
```
{
  "name": "yandex-checkout",
...
  "main": "./lib/index.js",
...
}
```
Пожалуйста, уточните окружение, в котором вы используете данный модуль

**Comment by vanya2h** [comment]
![2018-11-13 17 57 36](https://user-images.githubusercontent.com/16166451/48421475-9b6f1500-e76d-11e8-83ef-1cd80362af25.png)

Я думаю будет проще добавить index.js файл в корень и проблема исчезнет, если вдруг кто-то столкнется с такой же

**Comment by roman-kudlay-lodoss** [comment]
выпущена версия `1.0.12`

**Comment by roman-kudlay-lodoss** [comment]
@kv9991 Ошибка пропала?

**Comment by vanya2h** [comment]
@roman-kudlay-lodoss Все работает, оперативно вы
